defaults: &defaults
  working_directory: ~/repo
  environment:
    JRUBY_OPTS: -J-Xmx768M
    SELENIUM_URL: http://127.0.0.1:4444/wd/hub

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-jruby-1.7.26-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "pom.xml" }}
      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path=vendor/bundle
            bundle exec jbundle install
      - save_cache:
          paths:
            - ~/.m2
            - .bundle
            - .jbundler
            - vendor/bundle
          key: v1-dependencies-jruby-1.7.26-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format documentation \
                              --out /tmp/test-results/rspec.txt \
                              $(circleci tests glob "spec/*/*_spec.rb")
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  baid_spec:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
      - image: selenium/standalone-firefox:3.1.0
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-jruby-1.7.26-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "pom.xml" }}
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb firefox
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            if [ "${SIGNATURE}" != "" ]; then
              bundle exec jruby -S rspec ./spec/paypal_express/remote/baid_spec.rb | tee /tmp/test-results/baid_spec.txt 2>&1
            fi
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  hpp_spec:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
      - image: selenium/standalone-firefox:3.1.0
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-jruby-1.7.26-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "pom.xml" }}
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb firefox
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            if [ "${SIGNATURE}" != "" ]; then
              bundle exec jruby -S rspec ./spec/paypal_express/remote/hpp_spec.rb | tee /tmp/test-results/hpp_spec.txt 2>&1
            fi
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - baid_spec:
          requires:
            - build-and-test
      - hpp_spec:
          requires:
            - build-and-test
